Ejercicio Sobre Valores propios y vectores propios

In [1]:
from sympy import init_printing
init_printing(use_latex=True)
from sympy.physics.quantum import Dagger
from sympy import *
import numpy as np

DEFINICION DE LA MATRIZ

In [2]:
A=np.array([[4,-3,5],[-3,2,1],[5,1,-6]])

# Calculo de valores y vectores propios con la libreria Numpy#

In [3]:
import numpy.linalg as linalg
eigenValues, eigenVectors = linalg.eig(A)
eigenValues, eigenVectors

(array([-8.49593222,  7.22527225,  1.27065997]),
 array([[ 0.40509898,  0.85294674,  0.32920613],
        [ 0.2007686 , -0.43427565,  0.87812108],
        [-0.89195672,  0.2896317 ,  0.34716955]]))

Ahora se presentan los datos redondeados

In [4]:
np.round(eigenValues,1), np.round(eigenVectors,1)

(array([-8.5,  7.2,  1.3]),
 array([[ 0.4,  0.9,  0.3],
        [ 0.2, -0.4,  0.9],
        [-0.9,  0.3,  0.3]]))

In [16]:
P = eigenVectors.transpose()
P_inv = np.linalg.inv(P)
display(P)
display(P_inv)
D = np.round(np.matmul(np.matmul(P,A),P_inv),1)
display(D)

array([[ 0.40509898,  0.2007686 , -0.89195672],
       [ 0.85294674, -0.43427565,  0.2896317 ],
       [ 0.32920613,  0.87812108,  0.34716955]])

array([[ 0.40509898,  0.85294674,  0.32920613],
       [ 0.2007686 , -0.43427565,  0.87812108],
       [-0.89195672,  0.2896317 ,  0.34716955]])

array([[-8.5, -0. , -0. ],
       [ 0. ,  7.2,  0. ],
       [-0. , -0. ,  1.3]])